function initializeNewPaymentMethods(){const paymentWidgets=document.querySelectorAll("#payment-settings .widget");paymentWidgets.forEach((widget)=>{const title=widget.querySelector("h2").textContent.trim();const links=widget.querySelectorAll(".widget-content ul li a");if(title==="Paypal"){const paypalLink=links[0]?.getAttribute("href");if(paypalLink){const paypalButton=document.getElementById("paypal-redirect-button");if(paypalButton){paypalButton.setAttribute("data-paypal-link",paypalLink)}}}else if(title==="EasyPaisa"){const form=document.getElementById("easypaisa-form");if(links.length>=3&&form){form.querySelector(".info-box:nth-of-type(1) p").textContent=links[0].getAttribute("href");form.querySelector(".info-box:nth-of-type(2) p").textContent=links[1].getAttribute("href");form.querySelector(".qr-code").src=links[2].getAttribute("href")}}else if(title==="Bank Transfer"){const form=document.getElementById("bank-form");if(links.length>=4&&form){form.querySelector(".info-box:nth-of-type(1) p").textContent=links[0].getAttribute("href");form.querySelector(".info-box:nth-of-type(2) p").textContent=links[1].getAttribute("href");form.querySelector(".info-box:nth-of-type(3) p").textContent=links[2].getAttribute("href");form.querySelector(".info-box:nth-of-type(4) p").textContent=links[3].getAttribute("href")}}else if(title==="UPI Transfer"){const upiDetailsContainer=document.getElementById("upi-options-container-template");if(upiDetailsContainer){const upiOptionsContainer=document.createElement("div");upiOptionsContainer.className="upi-options-container";links.forEach((link)=>{const name=link.textContent.trim();const qrUrl=link.getAttribute("href");const optionDiv=document.createElement("div");optionDiv.className="upi-payment-option";optionDiv.innerHTML=`
                                <img src="${qrUrl}" alt="${name} UPI QR Code" class="qr-code">
                                <h3>${name}</h3>
                            `;upiOptionsContainer.appendChild(optionDiv)});upiDetailsContainer.appendChild(upiOptionsContainer)}}})}
let customerData={};let isProcessing=!1;function generateUUID(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){const r=(Math.random()*16)|0,v=c==="x"?r:(r&0x3)|0x8;return v.toString(16)})}
function generateOrderId(){const orders=JSON.parse(localStorage.getItem("bloggerStoreOrders")||"[]");const orderCount=orders.length+1;return `ORD-${1000 + orderCount}`}
function getCurrentCurrency(){const currencyDiv=document.querySelector("div.priceCurrency");if(currencyDiv&&currencyDiv.textContent.trim()!==""){return currencyDiv.textContent.trim()}
return"Rs"}
function validateEmail(email){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)}
function formatAddressForSheets(addr){const parts=[addr.name,addr.address,`${addr.city}, ${addr.state} ${addr.zip}`,addr.country,].filter((part)=>part&&part.trim()!=="Not provided"&&part.trim()!=="");return parts.join(" \n ")||"Address not provided"}
function formatAddressForDisplay(addr){return `${addr.name}\n${addr.address}\n${addr.city}, ${addr.state} ${addr.zip}\n${addr.country}`}
const checkoutCart={getCart:function(){try{const cart=localStorage.getItem("simpleCart");if(!cart||cart==="[]")return[];const parsedCart=JSON.parse(cart);return Array.isArray(parsedCart)?parsedCart.map((item)=>({id:item.id||"missing-id",title:item.title||"Untitled Product",image:item.image||"https://via.placeholder.com/80?text=No+Image",currentPrice:item.currentPrice||"$0.00",oldPrice:item.oldPrice||"",variant:item.variant||{},quantity:item.quantity||1,variantKey:item.variantKey||"",})):[]}catch(e){console.error("Error loading cart:",e);return[]}},getCurrency:function(){return getCurrentCurrency()},calculateTotals:function(){const cart=this.getCart();let subtotal=0;cart.forEach((item)=>{const priceStr=item.currentPrice.replace(/[^0-9.-]/g,"");const price=parseFloat(priceStr)||0;subtotal+=price*item.quantity});const shipping=this.calculateShipping(subtotal);const total=subtotal+shipping;return{subtotal,shipping,total}},calculateShipping:function(subtotal){if(subtotal===0)return 0;return subtotal>50?0:5.99},updateOrderSummary:function(){const cart=this.getCart();const currency=this.getCurrency();const cartItemsContainer=document.getElementById("cart-items");if(!cartItemsContainer)return;const totals=this.calculateTotals();cartItemsContainer.innerHTML="";if(cart.length===0){cartItemsContainer.innerHTML=`<div class="empty-cart-message"><i class="bi bi-bag-x"></i><p>Your cart is empty</p></div>`}else{cart.forEach((item)=>{const price=parseFloat(item.currentPrice.replace(/[^0-9.-]/g,""))||0;const itemTotal=price*item.quantity;let variantText="";if(item.variant&&typeof item.variant==="object"&&Object.keys(item.variant).length>0){variantText=Object.values(item.variant).filter((val)=>val&&val!=="undefined"&&val!==""&&val!==null).join(" / ")}
const itemElement=document.createElement("div");itemElement.className="cart-item";itemElement.innerHTML=`
                    <img src="${item.image}" alt="${item.title
                    }" loading="lazy" class="cart-item-image"
                         onerror="this.src='https://via.placeholder.com/80?text=Image+Error';">
                    <div class="cart-item-details">
                        <h4 class="cart-item-title">${item.title}</h4>
                        ${variantText
                        ? `<div class="cart-item-variant">${variantText}</div>`
                        : ""
                    }
                        <div class="cart-item-meta">
                            <span class="cart-item-quantity">Qty: ${item.quantity
                    }</span>
                            <span class="cart-item-price">${item.currentPrice
                    }</span>
                        </div>
                    </div>
                `;cartItemsContainer.appendChild(itemElement)})}
const subtotalEl=document.getElementById("cart-subtotal");if(subtotalEl)
subtotalEl.textContent=`${currency} ${totals.subtotal.toFixed(2)}`;const shippingEl=document.getElementById("cart-shipping");if(shippingEl)
shippingEl.textContent=totals.shipping===0?"Free":`${currency} ${totals.shipping.toFixed(2)}`;const totalEl=document.getElementById("cart-total");if(totalEl)totalEl.textContent=`${currency} ${totals.total.toFixed(2)}`;const codEl=document.getElementById("cod-total");if(codEl)codEl.textContent=`${currency} ${totals.total.toFixed(2)}`},getOrderDetailsHTML:function(){const cart=this.getCart();const currency=this.getCurrency();const totals=this.calculateTotals();if(cart.length===0)
return'<div class="empty-cart-message">Your cart is empty</div>';let itemsHTML=cart.map((item)=>{const price=parseFloat(item.currentPrice.replace(/[^0-9.-]/g,""))||0;const itemTotal=price*item.quantity;let variantText="";if(item.variant&&typeof item.variant==="object"&&Object.keys(item.variant).length>0){variantText=Object.values(item.variant).filter((val)=>val&&val!=="undefined"&&val!==""&&val!==null).join(" / ")}
return `
                <div class="cart-item">
                    <img src="${item.image}" alt="${item.title
                    }" loading="lazy" onerror="this.style.display='none';">
                    <div class="cart-item-details">
                        <h4>${item.title}</h4>
                        ${variantText ? `<div>${variantText}</div>` : ""}
                        <div><span>${item.quantity} × ${item.currentPrice
                    }</span></div>
                    </div>
                </div>
            `}).join("");return `
            <h3>Order Summary</h3>
            ${itemsHTML}
            <div class="order-totals">
                <div><h2> Your Order Details </h2></div>
                <div><h3>Subtotal</h3><span>${currency} <span style='margin-right: 10px;'></span> ${totals.subtotal.toFixed(
            2
        )}</span></div>
                <div><h3>Shipping</h3><span>${totals.shipping === 0
                ? "Free"
                : `${currency}<span style='margin-right: 10px;'></span>${totals.shipping.toFixed(2)}`
            }</span></div>
                <div><h3>Total</h3><span>${currency} <span style='margin-right: 10px;'></span> ${totals.total.toFixed(
                2
            )}</span></div>
            </div>
        `},};let currentTab="contact-section";let selectedPaymentMethod=null;function showTab(tabId){const tabs=["contact-section","shipping-section","selection","details"];const steps=["step-contact","step-shipping","step-selection","step-details",];tabs.forEach((tab)=>{const tabElement=document.getElementById(tab);if(tabElement)tabElement.classList.add("hidden");});steps.forEach((step)=>{const stepElement=document.getElementById(step);if(stepElement){stepElement.classList.remove("active","completed");const targetStep=`step-${tabId.replace("-section", "")}`;if(steps.includes(targetStep)){if(step===targetStep){stepElement.classList.add("active")}else if(steps.indexOf(step)<steps.indexOf(targetStep)){stepElement.classList.add("completed")}}}});const targetTab=document.getElementById(tabId);if(targetTab){targetTab.classList.remove("hidden");currentTab=tabId}
if(tabId==="details"&&selectedPaymentMethod)loadDetailsTab();}
function validateContact(){const email=document.getElementById("email")?.value.trim()||"";const emailError=document.getElementById("email-error");let isValid=!0;if(!validateEmail(email)){if(emailError)emailError.classList.remove("hidden");const emailInput=document.getElementById("email");if(emailInput)emailInput.classList.add("input-error");isValid=!1}else{if(emailError)emailError.classList.add("hidden");const emailInput=document.getElementById("email");if(emailInput)emailInput.classList.remove("input-error");}
return isValid}
function validateShipping(){const fields=["name","address","city","state","country","zip"];let isValid=!0;fields.forEach((field)=>{const input=document.getElementById(field);if(!input)return;const error=document.getElementById(`${field}-error`);const value=input.value.trim();if(!value){if(error)error.classList.remove("hidden");input.classList.add("input-error");isValid=!1}else{if(error)error.classList.add("hidden");input.classList.remove("input-error")}});if(!document.getElementById("same-as-shipping")?.checked){const billingFields=["checkout-billing-name","checkout-billing-address","checkout-billing-city","checkout-billing-state","checkout-billing-country","checkout-billing-zip",];billingFields.forEach((field)=>{const input=document.getElementById(field);if(!input)return;const error=document.getElementById(`${field}-error`);const value=input.value.trim();if(!value){if(error)error.classList.remove("hidden");input.classList.add("input-error");isValid=!1}else{if(error)error.classList.add("hidden");input.classList.remove("input-error")}})}
return isValid}
function validateAndProceedToDetails(){if(!selectedPaymentMethod){alert("Please select a payment method.");return}
showTab("details")}
function selectMethod(method){selectedPaymentMethod=method;document.querySelectorAll(".payment-option").forEach((option)=>option.classList.remove("selected"));const selectedOption=document.querySelector(`.payment-option[onclick="selectMethod('${method}')"]`);if(selectedOption)selectedOption.classList.add("selected");const nextButton=document.getElementById("next-button");if(nextButton)nextButton.classList.remove("hidden");}
function loadDetailsTab(){const formContent=document.getElementById("form-content");const paymentIcon=document.getElementById("payment-icon");if(!formContent)return;customerData={email:document.getElementById("email")?.value.trim()||"",phone:document.getElementById("phone")?.value.trim()||"",notes:document.getElementById("notes")?.value.trim()||"",paymentMethod:selectedPaymentMethod,shippingAddress:{name:document.getElementById("name")?.value.trim()||"Not provided",address:document.getElementById("address")?.value.trim()||"Not provided",city:document.getElementById("city")?.value.trim()||"Not provided",state:document.getElementById("state")?.value.trim()||"Not provided",country:document.getElementById("country")?.value.trim()||"Not provided",zip:document.getElementById("zip")?.value.trim()||"Not provided",},};if(document.getElementById("same-as-shipping")?.checked){customerData.billingAddress={...customerData.shippingAddress}}else{customerData.billingAddress={name:document.getElementById("checkout-billing-name")?.value.trim()||"Not provided",address:document.getElementById("checkout-billing-address")?.value.trim()||"Not provided",city:document.getElementById("checkout-billing-city")?.value.trim()||"Not provided",state:document.getElementById("checkout-billing-state")?.value.trim()||"Not provided",country:document.getElementById("checkout-billing-country")?.value.trim()||"Not provided",zip:document.getElementById("checkout-billing-zip")?.value.trim()||"Not provided",}}
const iconMap={cod:"https://img.icons8.com/color/48/000000/cash-in-hand.png",paypal:"https://upload.wikimedia.org/wikipedia/commons/a/a4/Paypal_2014_logo.png",easypaisa:"https://seeklogo.com/images/E/easypaisa-new-logo-412D450720-seeklogo.com.png",upi:"https://upload.wikimedia.org/wikipedia/commons/e/e1/UPI-Logo-vector.svg",bank:"https://uxwing.com/wp-content/themes/uxwing/download/banking-finance/bank-transfer-icon.png",};if(paymentIcon){paymentIcon.src=iconMap[selectedPaymentMethod]||"";paymentIcon.onerror=()=>{paymentIcon.src="https://via.placeholder.com/48?text=Pay"}}
const templateId=`${selectedPaymentMethod}-form`;const template=document.getElementById(templateId);const paymentFormContent=template?template.innerHTML:"";formContent.innerHTML=`
    ${paymentFormContent}
    <div class="customer-details-section" style="display:none;">
      <h3 class="section-title">Customer Information</h3>
      <div class="detail-row"><strong>Name:</strong> ${customerData.shippingAddress.name}</div>
    </div>
  `;bindPaymentMethodEvents()}
function bindPaymentMethodEvents(){function refreshCustomerDataFromFields(){customerData.email=document.getElementById("email")?.value.trim()||customerData.email||"";customerData.phone=document.getElementById("phone")?.value.trim()||customerData.phone||"";customerData.notes=document.getElementById("notes")?.value.trim()||customerData.notes||"";customerData.shippingAddress={name:document.getElementById("name")?.value.trim()||"Not provided",address:document.getElementById("address")?.value.trim()||"Not provided",city:document.getElementById("city")?.value.trim()||"Not provided",state:document.getElementById("state")?.value.trim()||"Not provided",country:document.getElementById("country")?.value.trim()||"Not provided",zip:document.getElementById("zip")?.value.trim()||"Not provided",};if(document.getElementById("same-as-shipping")?.checked){customerData.billingAddress={...customerData.shippingAddress}}else{customerData.billingAddress={name:document.getElementById("checkout-billing-name")?.value.trim()||"Not provided",address:document.getElementById("checkout-billing-address")?.value.trim()||"Not provided",city:document.getElementById("checkout-billing-city")?.value.trim()||"Not provided",state:document.getElementById("checkout-billing-state")?.value.trim()||"Not provided",country:document.getElementById("checkout-billing-country")?.value.trim()||"Not provided",zip:document.getElementById("checkout-billing-zip")?.value.trim()||"Not provided",}}}
if(selectedPaymentMethod==="paypal"){const paypalButton=document.getElementById("paypal-redirect-button");const confirmBtn=document.getElementById("paypal-confirm-button");let paypalLink=null;const widgets=document.querySelectorAll("#payment-settings .widget");widgets.forEach((widget)=>{const title=widget.querySelector("h2")?.textContent.trim().toLowerCase();if(title==="paypal"){const links=widget.querySelectorAll("a");const active=links[0]?.getAttribute("href")==="true";if(active&&links.length>1){paypalLink=links[1].getAttribute("href")}}});if(paypalButton){paypalButton.onclick=function(e){e.preventDefault();if(paypalLink){window.open(paypalLink,"_blank","noopener,noreferrer")}else{alert("PayPal is not active or link is missing.")}}}
if(confirmBtn){confirmBtn.onclick=function(e){e.preventDefault();refreshCustomerDataFromFields();if(paypalLink){processPayment("PayPal",e)}else{alert("PayPal is not active, cannot confirm order.")}}}}
if(selectedPaymentMethod==="bank"){const bankConfirmBtn=document.getElementById("bank-confirm-button");if(bankConfirmBtn){bankConfirmBtn.onclick=function(e){e.preventDefault();refreshCustomerDataFromFields();processPayment("Bank Transfer",e)}}}
if(selectedPaymentMethod==="easypaisa"){const easypaisaConfirmBtn=document.getElementById("easypaisa-confirm-button");if(easypaisaConfirmBtn){easypaisaConfirmBtn.onclick=function(e){e.preventDefault();refreshCustomerDataFromFields();processPayment("EasyPaisa",e)}}}
if(selectedPaymentMethod==="upi"){const upiConfirmBtn=document.getElementById("upi-confirm-button");if(upiConfirmBtn){upiConfirmBtn.onclick=function(e){e.preventDefault();refreshCustomerDataFromFields();processPayment("UPI Transfer",e)}}}}
function initializeNewPaymentMethods(){const paymentWidgets=document.querySelectorAll("#payment-settings .widget");paymentWidgets.forEach((widget)=>{const title=widget.querySelector("h2").textContent.trim();const links=widget.querySelectorAll(".widget-content ul li a");let isActive=!0;links.forEach((link)=>{if(link.textContent.trim().toLowerCase()==="active"){if(link.getAttribute("href").toLowerCase()==="false"){isActive=!1}}});if(!isActive){const optionMap={Paypal:"paypal",EasyPaisa:"easypaisa","Bank Transfer":"bank","UPI Transfer":"upi","Cash on Delivery":"cod",};const methodKey=optionMap[title];if(methodKey){const optionElement=document.querySelector(`.payment-option[onclick*="${methodKey}"]`);if(optionElement)optionElement.style.display="none"}
const formMap={Paypal:"paypal-form",EasyPaisa:"easypaisa-form","Bank Transfer":"bank-form","UPI Transfer":"upi-form",};const formId=formMap[title];if(formId){const formElement=document.getElementById(formId);if(formElement)formElement.style.display="none"}
return}
if(title==="Paypal"){const paypalLink=links[0]?.getAttribute("href");if(paypalLink){const paypalButton=document.getElementById("paypal-redirect-button");if(paypalButton){paypalButton.setAttribute("data-paypal-link",paypalLink);paypalButton.onclick=function(e){e.preventDefault();const link=paypalButton.getAttribute("data-paypal-link");if(link){window.open(link,"_blank")}else{alert("PayPal link is not set up yet.")}}}}}else if(title==="EasyPaisa"){const form=document.getElementById("easypaisa-form");if(form){links.forEach((link)=>{const label=link.textContent.trim().toLowerCase();if(label.includes("account name")){form.querySelector(".info-box:nth-of-type(1) p").textContent=link.getAttribute("href")}else if(label.includes("account number")){form.querySelector(".info-box:nth-of-type(2) p").textContent=link.getAttribute("href")}else if(label.includes("qr code")){form.querySelector(".qr-code").src=link.getAttribute("href")}})}}else if(title==="Bank Transfer"){const form=document.getElementById("bank-form");if(form){links.forEach((link)=>{const label=link.textContent.trim().toLowerCase();if(label.includes("account name")){form.querySelector(".info-box:nth-of-type(1) p").textContent=link.getAttribute("href")}else if(label.includes("account number")){form.querySelector(".info-box:nth-of-type(2) p").textContent=link.getAttribute("href")}else if(label.includes("bank name")){form.querySelector(".info-box:nth-of-type(3) p").textContent=link.getAttribute("href")}else if(label.includes("ifsc")){form.querySelector(".info-box:nth-of-type(4) p").textContent=link.getAttribute("href")}})}}else if(title==="UPI Transfer"){const upiDetailsContainer=document.getElementById("upi-options-container-template");if(upiDetailsContainer){const upiOptionsContainer=document.createElement("div");upiOptionsContainer.className="upi-options-container";links.forEach((link)=>{const label=link.textContent.trim().toLowerCase();if(label!=="active"){const name=link.textContent.trim();const qrUrl=link.getAttribute("href");const optionDiv=document.createElement("div");optionDiv.className="upi-payment-option";optionDiv.innerHTML=`
              <img src="${qrUrl}" alt="${name} UPI QR Code" class="qr-code">
              <h3>${name}</h3>
            `;upiOptionsContainer.appendChild(optionDiv)}});upiDetailsContainer.appendChild(upiOptionsContainer)}}})}
