document.addEventListener("DOMContentLoaded",function(){const alertMessage=document.getElementById("AlertMessage");if(alertMessage){const closeBtn=document.createElement("button");closeBtn.className="close-btn";closeBtn.innerHTML="&times;";closeBtn.addEventListener("click",function(){alertMessage.style.display="none"});alertMessage.appendChild(closeBtn)}
const linkList1=document.getElementById("LinkList1");const LayraMainMenu=document.getElementById("LayraMainMenu");const headerSection=document.getElementById("HeaderSection");let scrollYBeforeOpen=0;let isMenuLocked=!1;if(linkList1&&LayraMainMenu){const linkListOverlay=document.createElement("div");linkListOverlay.className="linklist-overlay";if(headerSection&&linkList1.parentNode){linkList1.parentNode.insertBefore(linkListOverlay,linkList1.nextSibling)}else{document.body.appendChild(linkListOverlay)}
const toggleBtn=document.createElement("button");toggleBtn.className="menu-toggle";toggleBtn.innerHTML='<i class="fa-solid fa-ellipsis-v"></i>';toggleBtn.setAttribute("aria-label","Open menu");const header1=document.getElementById("Header1");LayraMainMenu.insertBefore(toggleBtn,header1);toggleBtn.addEventListener("click",function(e){e.stopPropagation();if(isMenuLocked)return;scrollYBeforeOpen=window.scrollY||document.documentElement.scrollTop||0;linkList1.classList.add("active");linkListOverlay.classList.add("active");document.body.style.position='fixed';document.body.style.top=`-${scrollYBeforeOpen}px`;document.body.style.width='100%';isMenuLocked=!0});linkListOverlay.addEventListener("click",function(){closeMobileMenu()});function closeMobileMenu(){linkList1.classList.remove("active");linkListOverlay.classList.remove("active");if(isMenuLocked){document.body.style.position='';document.body.style.top='';document.body.style.width='';const target=scrollYBeforeOpen;setTimeout(()=>{window.scrollTo({top:target,behavior:'instant'})},20);isMenuLocked=!1}}
function createHierarchicalDropdown(){if(!linkList1)return;const ul=linkList1.querySelector("ul");if(!ul)return;const items=Array.from(ul.querySelectorAll("li"));const newUl=document.createElement("ul");let parentStack=[];const currentOpenDropdowns={};items.forEach((item)=>{const link=item.querySelector("a");if(!link)return;const text=link.textContent.trim();const level=(text.match(/^\/+/g)||[""])[0].length;link.textContent=text.replace(/^\/+/g,"");const newLi=document.createElement("li");newLi.innerHTML=item.innerHTML;if(level===0){parentStack=[{element:newLi,container:null,level:0}];newUl.appendChild(newLi)}else{while(parentStack.length>0&&parentStack[parentStack.length-1].level>=level){parentStack.pop()}
if(parentStack.length===0){parentStack=[{element:newLi,container:null,level:0}];newUl.appendChild(newLi);return}
const parent=parentStack[parentStack.length-1];if(!parent.container){const container=document.createElement("div");container.className="dropdown-container";container.dataset.level=level;const parentLink=parent.element.querySelector("a");const icon=document.createElement("i");icon.className="fa-solid fa-plus dropdown-icon";parentLink.appendChild(icon);const dropdownUl=document.createElement("ul");dropdownUl.className="dropdown-menu";container.appendChild(dropdownUl);parent.element.appendChild(container);parent.container=container}
parent.container.querySelector("ul").appendChild(newLi);parentStack.push({element:newLi,container:null,level:level})}});ul.replaceWith(newUl);document.querySelectorAll(".dropdown-container").forEach((container)=>{const parentLink=container.parentElement.querySelector("a");if(!parentLink)return;parentLink.addEventListener("click",function(e){const icon=this.querySelector(".dropdown-icon");if(!icon)return;e.preventDefault();const dropdown=container.querySelector("ul");const level=container.dataset.level;if(container.classList.contains("open")){dropdown.style.maxHeight=dropdown.scrollHeight+"px";setTimeout(()=>dropdown.style.maxHeight="0",10);setTimeout(()=>{container.classList.remove("open");icon.classList.replace("fa-minus","fa-plus");dropdown.style.maxHeight="";delete currentOpenDropdowns[level]},300)}else{if(currentOpenDropdowns[level]&&currentOpenDropdowns[level]!==container){const prevContainer=currentOpenDropdowns[level];const prevIcon=prevContainer.parentElement.querySelector(".dropdown-icon");const prevDropdown=prevContainer.querySelector("ul");prevDropdown.style.maxHeight=prevDropdown.scrollHeight+"px";setTimeout(()=>prevDropdown.style.maxHeight="0",10);setTimeout(()=>{prevContainer.classList.remove("open");prevIcon.classList.replace("fa-minus","fa-plus");prevDropdown.style.maxHeight=""},300)}
container.classList.add("open");icon.classList.replace("fa-plus","fa-minus");dropdown.style.maxHeight="0";setTimeout(()=>dropdown.style.maxHeight=dropdown.scrollHeight+"px",10);setTimeout(()=>{dropdown.style.maxHeight="";currentOpenDropdowns[level]=container},300)}})});function resetAllDropdowns(){document.querySelectorAll(".dropdown-container.open").forEach((container)=>{const icon=container.parentElement.querySelector(".dropdown-icon");const dropdown=container.querySelector("ul");dropdown.style.maxHeight=dropdown.scrollHeight+"px";setTimeout(()=>dropdown.style.maxHeight="0",10);setTimeout(()=>{container.classList.remove("open");icon.classList.replace("fa-minus","fa-plus");dropdown.style.maxHeight=""},300)});Object.keys(currentOpenDropdowns).forEach(level=>delete currentOpenDropdowns[level])}
if(linkList1){const observer=new MutationObserver((mutations)=>{mutations.forEach((mutation)=>{if(mutation.attributeName==="style"||mutation.attributeName==="class"){const isHidden=linkList1.offsetParent===null||window.getComputedStyle(linkList1).display==="none";if(isHidden)resetAllDropdowns();}})});observer.observe(linkList1,{attributes:!0})}}
createHierarchicalDropdown();if(linkList1){const topLevelItems=linkList1.querySelectorAll("ul > li");let visibleIndex=0;topLevelItems.forEach((item)=>{const link=item.querySelector("a");if(link){const text=link.textContent.trim();if(!/^_+/.test(text)){const delay=0.2+visibleIndex*0.1;item.style.transitionDelay=`${delay}s`;visibleIndex++}}})}
function addSidebarCloseIcon(){if(!linkList1)return;const closeBtn=document.createElement("button");closeBtn.className="close-panel";closeBtn.title="Close";closeBtn.innerHTML='<i class="bi bi-x"></i>';closeBtn.addEventListener("click",function(e){e.stopPropagation();closeMobileMenu()});const widgetContent=linkList1.querySelector(".widget-content");if(widgetContent){const panelHeader=document.createElement("div");panelHeader.className="panel-header";panelHeader.style.marginBottom="20px";panelHeader.style.paddingBottom="20px";panelHeader.style.borderBottom="1px solid var(--border-color)";const title=document.createElement("h3");title.textContent="Menu";panelHeader.appendChild(title);panelHeader.appendChild(closeBtn);widgetContent.insertBefore(panelHeader,widgetContent.firstChild)}}
addSidebarCloseIcon()}
const searchObserver=new MutationObserver((mutations,obs)=>{const searchInput=document.querySelector(".gsc-input input");if(searchInput){searchInput.placeholder="Search here......";obs.disconnect()}});searchObserver.observe(document.body,{childList:!0,subtree:!0})});(function(){"use strict";const header=document.getElementById("HeaderSection");const spacer=document.querySelector(".header-spacer");if(!header||!spacer)return;const headerHeight=header.offsetHeight;let lastScroll=0;let isFixed=!1;window.addEventListener("scroll",()=>{const currentScroll=window.pageYOffset||document.documentElement.scrollTop;if(currentScroll>lastScroll&&currentScroll>headerHeight&&!isFixed){header.classList.add("is-fixed");spacer.style.height=headerHeight+"px";isFixed=!0}
if(currentScroll<lastScroll&&isFixed){header.classList.remove("is-fixed");spacer.style.height="0px";isFixed=!1}
lastScroll=currentScroll<=0?0:currentScroll})})();(function(){"use strict";function decodeHTML(html){const t=document.createElement("textarea");t.innerHTML=html||"";return t.value}
function extractShortcode(href){if(!href)return null;const m=href.match(/\[mega-menu\/(.+?)\/(\d+)\]/i);if(!m)return null;return{type:m[1].trim(),count:parseInt(m[2],10)||5}}
function extract(body,key){const r=new RegExp("\\["+key+"=([^\\]]+)\\]","i");const m=body.match(r);return m?m[1].trim():""}
function getImage(entry){try{const html=entry.content?.$t||entry.summary?.$t||"";const d=document.createElement("div");d.innerHTML=decodeHTML(html);const img=d.querySelector("img")||entry.media$thumbnail;if(!img)return"";return(img.src||img.url||"").replace(/\/s\d+(-c)?\//g,"/s120/").replace(/\/w\d+-h\d+\//g,"/s120/")}catch{return""}}
function getCurrency(){return document.querySelector(".priceCurrency")?.textContent.trim()||""}
function sanitizeNumber(val){if(!val)return"";return val.replace(/[^0-9.]/g,"")}
function formatPrice(number,currency){if(!number)return"";const parts=number.split(".");let intPart=parts[0];const decPart=parts[1]?"."+parts[1]:"";intPart=intPart.replace(/\B(?=(\d{3})+(?!\d))/g,",");return currency?`${currency} ${intPart}${decPart}`:`${intPart}${decPart}`}
function formatSale(val){if(!val)return"";val=val.replace(/["']/g,"").trim();if(val.startsWith("-")&&val.includes("%")){return val.replace("-","")+" OFF"}
return""}
async function buildMegaMenu(anchor,type,count){const site=location.origin;const t=type.toLowerCase();let feedUrl;if(t==="recent"){feedUrl=`${site}/feeds/posts/default?alt=json&max-results=${count}`}else if(t==="random"){feedUrl=`${site}/feeds/posts/default?alt=json&max-results=${count * 2}`}else{const labelName=type.replace(/\s+/g," ").trim();feedUrl=`${site}/feeds/posts/default/-/${encodeURIComponent(labelName)}?alt=json&max-results=${count}`}
let data;try{data=await fetch(feedUrl).then(r=>r.json())}catch{return}
let posts=data.feed?.entry||[];if(t==="random")
posts=posts.sort(()=>0.5-Math.random()).slice(0,count);else posts=posts.slice(0,count);if(!posts.length){anchor.parentElement.classList.remove("has-mega-menu");return}
const currency=getCurrency();const menu=document.createElement("div");menu.className="Layra-mega-menu";menu.innerHTML=`
            <ul class="Layra-mega-posts">
                ${posts.map(p => {
            const body = p.content?.$t || "";
            const title = p.title.$t;
            const url = p.link.find(l => l.rel === "alternate")?.href || "#";
            const img = getImage(p);
            const rawPrice = sanitizeNumber(extract(body, "current-price"));
            const price = rawPrice ? formatPrice(rawPrice, currency) : "";
            const sale = formatSale(extract(body, "sale"));
            return `<li class="mega-post-item"><a href="${url}">${img?`<img src="${img}" loading="lazy">`:""}<div class="mega-post-info"><span class="mega-title">${title}</span><div class='mega-price-info'>${price?`<span class="mega-price">${price}</span>`:""}
${sale?`<span class="mega-sale">${sale}</span>`:""}</div></div></a></li>`;
        }).join("")}
            </ul>
        `;anchor.parentElement.appendChild(menu)}
function initMegaMenus(){document.querySelectorAll("#HeaderSection a").forEach(anchor=>{const href=anchor.getAttribute("href");const data=extractShortcode(href);if(!data)return;anchor.setAttribute("href","javascript:void(0)");if(!anchor.querySelector(".mega-icon")){const icon=document.createElement("i");icon.className="fa-solid fa-plus mega-icon";icon.style.marginLeft="6px";anchor.appendChild(icon)}
const li=anchor.closest("li");if(!li)return;li.classList.add("has-mega-menu");buildMegaMenu(anchor,data.type,data.count);anchor.addEventListener("click",function(e){e.preventDefault();li.classList.toggle("mega-open");const icon=anchor.querySelector(".mega-icon");if(icon){icon.classList.toggle("fa-plus");icon.classList.toggle("fa-minus")}})})}
if(document.readyState==="loading")
document.addEventListener("DOMContentLoaded",initMegaMenus);else initMegaMenus()})()
